#define _BSD_SOURCE 1
#define _POSIX_C_SOURCE 199309

#include <stdlib.h>
#include <assert.h>
#include <stdio.h>
#include <string.h>

#include "rac24.h"

#define MAX_RANGE_BITS 24
#define MIN_RANGE_BITS (MAX_RANGE_BITS-8)
#define MIN_RANGE (1ULL << (rac24_t)(MIN_RANGE_BITS))

#define BASE_RANGE (1ULL << MAX_RANGE_BITS)

void rac24_init_enc(rac24_ctx_t *ctx, void(*writefn)(void *, int), void *data) {
  ctx->range = BASE_RANGE;
  ctx->low = 0;
  ctx->delayed_byte = -1;
  ctx->delayed_count = 0;
  ctx->writefn = writefn;
  ctx->readfn = NULL;
  ctx->data = data;
}

void rac24_init_dec(rac24_ctx_t *ctx, int(*readfn)(void *), void *data) {
  ctx->low = 0;
  rac24_t r = BASE_RANGE;
  while (r > 1) {
    ctx->low <<= 8;
    ctx->low |= readfn(data);
    r >>= 8;
  }
  ctx->range = BASE_RANGE;
  ctx->readfn = readfn;
  ctx->writefn = NULL;
  ctx->data = data;
}

void static rac24_read(rac24_ctx_t *ctx) {
  while (ctx->range <= MIN_RANGE) {
    ctx->low <<= 8;
    ctx->range <<= 8;
    ctx->low |= ctx->readfn(ctx->data);
  }
}

void static rac24_write(rac24_ctx_t *ctx) {
  while (ctx->range <= MIN_RANGE) {
    int byte = ctx->low >> MIN_RANGE_BITS;
    if (ctx->delayed_byte < 0) { // first generated byte
      ctx->delayed_byte = byte;
    } else if (ctx->low + ctx->range < 0x100 * MIN_RANGE) { // definitely no overflow
      ctx->writefn(ctx->data,ctx->delayed_byte);
      while (ctx->delayed_count) {
        ctx->writefn(ctx->data,0xFF);
        ctx->delayed_count--;
      }
      ctx->delayed_byte = byte;
    } else if (ctx->low >= 0x100ULL * MIN_RANGE) { // definitely overflow
      ctx->writefn(ctx->data,ctx->delayed_byte + 1);
      while (ctx->delayed_count) {
        ctx->writefn(ctx->data,0x00);
        ctx->delayed_count--;
      }
      ctx->delayed_byte = byte & 0xFF;
    } else { // possibly overflow
      ctx->delayed_count++;
    }
    ctx->low = (ctx->low & (MIN_RANGE - 1)) << 8;
    ctx->range <<= 8;
  }
}

#define put_bit(ctx,chs,val) { \
  assert(chs>0); \
  assert(chs < ctx->range); \
  if (val) { \
    ctx->low += ctx->range - chs; \
    ctx->range = chs; \
  } else { \
    ctx->range -= chs; \
  } \
  rac24_write(ctx); \
}

#define get_bit(ctx,chs) { \
  assert(chs>0); \
  assert(chs < ctx->range); \
  if (ctx->low >= ctx->range - chs) { \
    ctx->low -= ctx->range - chs; \
    ctx->range = chs; \
    rac24_read(ctx); \
    return 1; \
  } else { \
    ctx->range -= chs; \
    rac24_read(ctx); \
    return 0; \
  } \
}

void rac24_put_bit_frac(rac24_ctx_t *ctx, int num, int denom, int value) {
  assert(num>=0);
  assert(num<denom);
  assert(denom>1);
  rac24_t chs = (ctx->range / denom) * num;
  put_bit(ctx,chs,value);
}

void rac24_put_bit_b16(rac24_ctx_t *ctx, uint16_t b16, int value) {
  uint64_t r = ctx->range;
  rac24_t chs = (r * b16 + 0x8000) >> 16;
  put_bit(ctx,chs,value);
}

int rac24_get_bit_frac(rac24_ctx_t *ctx, int num, int denom) {
  assert(num>=0);
  assert(num<denom);
  assert(denom>1);
  rac24_t chs = (ctx->range / denom) * num;
  get_bit(ctx,chs);
}

int rac24_get_bit_b16(rac24_ctx_t *ctx, uint16_t b16) {
  uint64_t r = ctx->range;
  rac24_t chs = (r * b16 + 0x8000) >> 16;
  get_bit(ctx,chs);
}

void rac24_flush(rac24_ctx_t *ctx) {
  ctx->low += (MIN_RANGE - 1);
  ctx->range = (MIN_RANGE - 1);
  rac24_write(ctx);
  ctx->range = (MIN_RANGE - 1);
  rac24_write(ctx);
  rac24_init_enc(ctx,ctx->writefn,ctx->data);
}
